name: Main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup
        run: |
          mkdir public
      
      - name: Copy index
        run: cp index.html public/index.html

      - name: Copy static pages
        run: |
          cp -a ./docs-page ./public/docs-page
          cp -a ./survey-form ./public/survey-form
          cp -a ./landing-page ./public/landing-page
          cp -a ./portfolio-project ./public/portfolio-project
          cp -a ./tribute-page ./public/tribute-page
          cp -a ./quote-machine ./public/quote-machine

      - name: Build & copy markdown viewer
        run: |
          cd ./md-viewer
          npm install
          npm run build
          mv ./build ../public/md-viewer
          cd ../
      
      - name: Build & copy drum machine
        run: |
          cd ./drum-machine
          npm install
          npm run build
          mv ./build ../public/drum-machine
          cd ../

      - name: Build & copy calculator
        run: |
          cd ./calculator
          npm install
          npm run build
          mv ./build ../public/calculator
          cd ../

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4