name: Main
on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Setup
              run: |
                mkdir public
            
            - name: Copy index
              run: cp index.html public/index.html

            - name: Copy static pages
              run: |
                cp -a ./docs-page ./public/docs-page
                cp -a ./survey-form ./public/survey-form
                cp -a ./landing-page ./public/landing-page
                cp -a ./portfolio-project ./public/portfolio-project
                cp -a ./tribute-page ./public/tribute-page

            - name: Build & copy markdown viewer
              run: |
                cd ./md-viewer
                npm install
                npm run build
                mv ./public ./md-viewer
                cp -a ./md-viewer ../public/md-viewer
                cd ../
            
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: public